### ISSUE TITLE
[Bug] Database warning: (models.W042) Auto-created primary key used when not defining a primary key type

### ISSUE THREAD

**Issue by TimidRobot** [creativecommons/legaldb#121]
## Description
```
WARNINGS:
legal_db.Case: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the LegalDBConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
legal_db.FAQ: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the LegalDBConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
legal_db.Link: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the LegalDBConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
legal_db.Scholarship: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
        HINT: Configure the DEFAULT_AUTO_FIELD setting or the LegalDBConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
```

## Reproduction
do most any Django thing

## Expectation
- Application should run without warnings
- Need to find documentation on Django migrations on Heroku

## Additional context
- [**Customizing type of auto-created primary keys** | Django 3.2 release notes | Django documentation | Django](https://docs.djangoproject.com/en/4.0/releases/3.2/#customizing-type-of-auto-created-primary-keys)
